@echo off
echo Simulando entorno de Railway...

REM Guardar variables actuales
set CURRENT_DATABASE_URL=%DATABASE_URL%
set CURRENT_DATABASE_SSL=%DATABASE_SSL%
set CURRENT_DATABASE_SSL_REJECT_UNAUTHORIZED=%DATABASE_SSL_REJECT_UNAUTHORIZED%
set CURRENT_RAILWAY=%RAILWAY%

REM Configurar variables de Railway
set DATABASE_URL=postgresql://postgres:ominey@localhost:5432/fixedv4
set DATABASE_SSL=true
set DATABASE_SSL_REJECT_UNAUTHORIZED=false
set RAILWAY=true

echo Variables de entorno configuradas para Railway:
echo DATABASE_URL=%DATABASE_URL%
echo DATABASE_SSL=%DATABASE_SSL%
echo DATABASE_SSL_REJECT_UNAUTHORIZED=%DATABASE_SSL_REJECT_UNAUTHORIZED%
echo RAILWAY=%RAILWAY%

echo Iniciando Strapi en modo Railway...
npm run develop

REM Restaurar variables originales
set DATABASE_URL=%CURRENT_DATABASE_URL%
set DATABASE_SSL=%CURRENT_DATABASE_SSL%
set DATABASE_SSL_REJECT_UNAUTHORIZED=%CURRENT_DATABASE_SSL_REJECT_UNAUTHORIZED%
set RAILWAY=%CURRENT_RAILWAY%
